spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true

    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 100

  jwt:
    access-secret: TestSecretKey123asdasdadadwadwawdawdadwddwawdadwadawadwdwaawdawdwaddwadwawad
    access-expire-min: 30
    refresh-secret: TestRefreshKey2131asdsdasdwdwadawdawdwadwadawwadawdawdwadwadawdawdwadawdwad
    refresh-expire-min: 1440

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  profiles:
    group:
      "local": "local"
      "development": "development"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    url: jdbc:h2:mem:zero
    username: zero
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true



