name: githubActionTest
on:
  push:
    branches : [ main ]
jobs:
  build:
    runs-on: ubuntu-latest # 운영체제 지정
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files : ${{ secrets.RESOURCE_PATH }}
        env:
          spring.jpa.defer-defer-datasource-initialization: true
          spring.jpa.generate-ddl: true
          spring.jpa.hibernate.ddl-auto: update
          spring.jpa.open-in-view: false
          spring.jpa.properties.hibernate.format_sql: true
          spring.jpa.properties.hibernate.show_sql: true
          spring.jpa.properties.hibernate.jdbc.batch_size: 100
          spring.jwt.access-secret: ${{ secrets.ACCESS_SECRET }}
          spring.jwt.refresh-secret: ${{ secrets.REFRESH_SECRET }}
          spring.jwt.access-expire-min: 30
          spring.jwt.refresh-expire-min: 30
          spring.mvc.pathmatch.matching-strategy: ant_path_matcher
          spring.datasource.url: jdbc:h2:mem:zero
          spring.datasource.username: zero
          spring.datasource.driver-class-name: org.h2.Driver
          spring.h2.console.enabled: true
          
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-developer ]
    steps:
      - name: deploy run
        run: |
          sudo sh /home/ec2-user/success.sh #ec2-user
