name: 제로기프트 빌드 자동화

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO: module-api
      working-directory: ./module-api

    steps:
      - name: 프로젝트 체크아웃합니다.
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: recursive

      - name: JDK 11을 설치합니다.
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: '6'

      - name: Gradle 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew

      - name: Build and analyze
        run: ./gradlew clean build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./module-api
          file: ./module-api/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.REPO}}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: deploy run
        run: |
          sudo sh /home/ec2-user/deploy.sh